const API_URL=""; // Inserire qui l'URL della Web App Google Apps Script quando sarà pubblicata.
const KEY="adinolfi_agenda_v1";
const pad=n=>String(n).padStart(2,"0");
const iso=d=>d.getFullYear()+"-"+pad(d.getMonth()+1)+"-"+pad(d.getDate());
const today=iso(new Date());
let events=JSON.parse(localStorage.getItem(KEY)||"[]");
let filter="all"; let deferredInstall=null;
const $=id=>document.getElementById(id);
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(events))}
function weekBounds(){const d=new Date();const day=(d.getDay()+6)%7;const a=new Date(d);a.setHours(0,0,0,0);a.setDate(d.getDate()-day);const b=new Date(a);b.setDate(a.getDate()+6);b.setHours(23,59,59,999);return[a,b]}
function inWeek(e){if(!e.date)return false;const [a,b]=weekBounds(),d=new Date(e.date+"T12:00:00");return d>=a&&d<=b}
function matches(e){const q=$("search").value.trim().toLowerCase(),cat=$("cat").value;if(cat!=="all"&&e.category!==cat)return false;if(q&&!(e.title+" "+e.desc+" "+e.category).toLowerCase().includes(q))return false;if(filter==="today"&&e.date!==today)return false;if(filter==="week"&&!inWeek(e))return false;if(filter==="todo"&&e.status==="Completato")return false;if(filter==="high"&&e.priority!=="Alta")return false;return true}
function render(){const list=$("list");const arr=[...events].sort((a,b)=>(a.date||"9999").localeCompare(b.date||"9999")||(a.time||"99").localeCompare(b.time||"99"));const v=arr.filter(matches);list.innerHTML="";if(!v.length){list.innerHTML='<div class="empty">Nessun impegno trovato.</div>'}else v.forEach(e=>{const d=e.date?new Date(e.date+"T12:00:00").toLocaleDateString("it-IT",{weekday:"short",day:"2-digit",month:"2-digit",year:"numeric"}):"Data da definire";const x=document.createElement("div");x.className="event "+e.priority.toLowerCase();x.innerHTML='<div class="bar"></div><div><h3>'+esc(e.title)+'</h3><div class="meta">'+d+(e.time?" · "+esc(e.time):"")+'</div><div><span class="badge">'+esc(e.category)+'</span><span class="badge">'+esc(e.priority)+'</span><span class="badge">'+esc(e.status)+'</span></div><div class="meta">'+esc(e.desc)+'</div></div><div class="actions"><button data-edit="'+e.id+'">Modifica</button><button data-done="'+e.id+'">'+(e.status==="Completato"?"Riapri":"Completa")+'</button></div>';list.appendChild(x)});$("sToday").textContent=events.filter(e=>e.date===today).length;$("sWeek").textContent=events.filter(inWeek).length;$("sTodo").textContent=events.filter(e=>e.status!=="Completato").length;$("sHigh").textContent=events.filter(e=>e.priority==="Alta"&&e.status!=="Completato").length}
function reset(){ $("id").value=""; $("date").value=today; $("time").value=""; $("title").value=""; $("desc").value=""; $("priority").value="Media"; $("reminder").value="Nessuno" }
$("form").addEventListener("submit",async ev=>{ev.preventDefault();const id=$("id").value||String(Date.now());const item={id,date:$("date").value,time:$("time").value,category:$("category").value,title:$("title").value.trim(),desc:$("desc").value.trim(),priority:$("priority").value,reminder:$("reminder").value,status:"Da fare"};const i=events.findIndex(x=>x.id===id);if(i>=0){item.status=events[i].status;events[i]=item}else events.push(item);saveLocal();render();if(API_URL)try{await fetch(API_URL,{method:"POST",body:JSON.stringify({action:"upsert",event:item})})}catch(_){$("sync").textContent="Salvato localmente; sincronizzazione cloud non riuscita."}reset()});
$("cancel").onclick=reset;$("newBtn").onclick=()=>{reset();$("title").focus()};$("search").oninput=render;$("cat").onchange=render;
document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x===b));render()});
$("list").addEventListener("click",async ev=>{const edit=ev.target.closest("[data-edit]"),done=ev.target.closest("[data-done]");const id=(edit||done)?.dataset?.[edit?"edit":"done"];if(!id)return;const e=events.find(x=>x.id===id);if(!e)return;if(edit){Object.entries({id:e.id,date:e.date,time:e.time,category:e.category,title:e.title,desc:e.desc,priority:e.priority,reminder:e.reminder}).forEach(([k,v])=>$(k).value=v);$("formPanel").scrollIntoView({behavior:"smooth",block:"start"})}else{e.status=e.status==="Completato"?"Da fare":"Completato";saveLocal();render();if(API_URL)try{await fetch(API_URL,{method:"POST",body:JSON.stringify({action:"upsert",event:e})})}catch(_){}}});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;$("install").hidden=false});$("install").onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$("install").hidden=true}};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
reset();render();